baz_scheduler/urls.py
from django.urls import include, path
from . import views


app_name = 'baz_scheduler'
urlpatterns = [
    path('', views.index, name='index'),
    path('baz/<int:pk>/', views.BazDetailView.as_view(), name='baz-details'),
    path('baz/create/', views.BazCreateView.as_view(), name='baz-create'),
    path('baz/update/<int:pk>/', views.BazUpdateView.as_view(), name='baz-update'),
    path('baz/delete/<int:pk>/', views.BazDeleteView.as_view(), name='baz-delete'),
    path('baz/thanks/', views.baz_thanks, name='baz-thanks'),

    path('sent_baz/<int:pk>/', views.SentBazDetailView.as_view(), name='sent-baz-details'),
    path('sent_baz/create/', views.SentBazCreateView.as_view(), name='sent-baz-create'),
    path('sent_baz/update/<int:pk>/', views.SentBazUpdateView.as_view(), name='sent-baz-update'),
    path('sent_baz/delete/<int:pk>/', views.SentBazDeleteView.as_view(), name='sent-baz-delete'),
    path('sent_baz/thanks/', views.sent_baz_thanks, name='sent-baz-thanks'),

    path('employee/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee-details'),
    path('employee/create/', views.EmployeeCreateView.as_view(), name='employee-create'),
    path('employee/update/<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee/delete/<int:pk>/', views.EmployeeDeleteView.as_view(), name='employee-delete'),
    path('employee/thanks/', views.employee_thanks, name='employee-thanks'),

    path('customer/<int:pk>/', views.CustomerDetailView.as_view(), name='customer-details'),
    path('customer/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/update/<int:pk>/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='customer-delete'),
    path('customer/thanks/', views.customer_thanks, name='customer-thanks'),

    path('api-auth/', include('baz_scheduler.rest_urls', namespace='rest_framework'))
]

cybeready/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('bazs/', include('baz_scheduler.urls')),
    path('admin/', admin.site.urls),
]

baz_scheduler/models.py
# Describe all the entities models and relationships between them

from django.db import models
from django.shortcuts import reverse
from django.utils.timezone import now, datetime
from django.core.validators import MaxValueValidator, MinValueValidator


class Customer(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False, blank=False)
    manager_email = models.EmailField(null=False, blank=False, unique=True)

    def __str__(self):
        return f'{self.name}, ({self.manager_email})'


class Employee(models.Model):
    customer = models.ForeignKey(to=Customer, on_delete=models.CASCADE, blank=False, null=False)
    email = models.EmailField(blank=False, null=False, unique=True)
    first_name = models.CharField(max_length=50)
    second_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.email}'

    def get_absolute_url(self):
        return reverse('baz_scheduler:employee-details', args=(self.pk,))


class Baz(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    subject = models.CharField(max_length=100)
    content = models.TextField(max_length=2000)
    malicious_link = models.URLField(blank=False, null=False)
    start_spreading = models.DateTimeField(default=now, auto_created=True, blank=False, null=False)
    target = models.ManyToManyField(to=Employee, through='SentBaz')
    scheduling_interval = models.PositiveIntegerField(blank=False, null=False, validators=[MinValueValidator(1), MaxValueValidator(4)])
    future_sending_delta = models.DateTimeField(blank=True, null=True)

    # def save(self, *args, **kwargs):
    #     if self.future_scheduled_sending_shift and self.future_scheduled_sending_shift <= self.start_spreading:
    #         raise ValueError('Future sending should be later than beginning')

    #     return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} ({self.subject})'

    def get_absolute_url(self):
        return reverse('baz_scheduler:baz-details', args=(self.pk,))


class SentBaz(models.Model):
    employee = models.ForeignKey(to=Employee, on_delete=models.CASCADE, blank=False)
    baz = models.ForeignKey(to=Baz, on_delete=models.CASCADE, blank=False)
    last_sent_on = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    sent_success = models.BooleanField(default=False, null=False, blank=False)
    opened_by_target = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return f'{self.baz_set[:5]}'

    def get_absolute_url(self):
        return reverse('baz_scheduler:sent-baz-detail', kwargs={'pk': self.pk})

    class Meta:
        # Ensure there is a single "interaction" between Baz and target
        unique_together = (('employee', 'baz',))

baz_scheduler/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import Baz, Customer, Employee, SentBaz
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView


class BazDetailView(DetailView):
    model = Baz

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['obj'] = kwargs['object']
        return context

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class BazCreateView(CreateView):
    model = Baz
    fields = ['name', 'subject', 'content', 'send_interval']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('baz_scheduler:baz-thanks')

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class BazUpdateView(UpdateView):
    model = Baz
    fields = ['name']
    template_name_suffix = '_update_form'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class BazDeleteView(DeleteView):
    model = Baz
    success_url = reverse_lazy('baz_scheduler:baz-thanks')


def baz_thanks(request):
    return HttpResponse('Thanks.')


class CustomerDetailView(DetailView):
    model = Customer

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['obj'] = kwargs['object']
        return context

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class CustomerCreateView(CreateView):
    model = Customer
    fields = ['name', 'manager_email']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('baz_scheduler:customer-thanks')

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class CustomerUpdateView(UpdateView):
    model = Customer
    fields = ['name', 'manager_email']
    template_name_suffix = '_update_form'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class CustomerDeleteView(DeleteView):
    model = Customer
    success_url = reverse_lazy(f'baz_scheduler:customer-thanks')

    def delete(self, request, *args, **kwargs):
        print(self.get_object())
        return super().delete(request, *args, **kwargs)


def customer_thanks(request):
    return HttpResponse('Thanks.')


class EmployeeDetailView(DetailView):
    model = Employee

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['obj'] = kwargs['object']
        return context

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class EmployeeCreateView(CreateView):
    model = Employee
    fields = ['email', 'first_name', 'second_name', 'customer']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('baz_scheduler:employee-thanks')

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class EmployeeUpdateView(UpdateView):
    model = Employee
    fields = ['name']
    template_name_suffix = '_update_form'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = reverse_lazy('baz_scheduler:employee-thanks')


def employee_thanks(request):
    return HttpResponse('Thanks.')


class SentBazDetailView(DetailView):
    model = SentBaz

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['obj'] = kwargs['object']
        return context

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class SentBazCreateView(CreateView):
    model = SentBaz
    fields = ['customers', 'bazs']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('baz_scheduler:employee-thanks')

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class SentBazUpdateView(UpdateView):
    model = SentBaz
    fields = ['name', 'manager_email']
    template_name_suffix = '_update_form'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class SentBazDeleteView(DeleteView):
    model = SentBaz
    success_url = reverse_lazy('baz_scheduler:sent-baz-thanks')


def sent_baz_thanks(request):
    return HttpResponse('Thanks.')


def index(request):
    return HttpResponse('Index page')

baz_scheduler/templates/baz_scheduler/baz_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete the baz?</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Delete">Delete baz</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/baz_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create baz</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Create</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/baz_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Baz details</title>
</head>
<body>
    Baz name = {{ obj.name }}
    <br />
    <a href="{% url 'baz_scheduler:baz-update' obj.pk %}">Edit</a>
    <a href="{% url 'baz_scheduler:baz-create' %}">Create a new Baz</a>
    <a href="{% url 'baz_scheduler:baz-delete' obj.pk %}">Delete the Baz</a>
</body>
</html>

baz_scheduler/templates/baz_scheduler/baz_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update baz</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Update</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/customer_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm customer delete</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Delete">Delete customer</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/customer_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create customer</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Create</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/customer_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update customer</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Update</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/employee_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create employee</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Create</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/employee_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update employee</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Update</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/empployee_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee details</title>
</head>
<body>
    Employee name = {{ obj.name }}
    <br />
    <a href="{% url 'baz_scheduler:employee-update' obj.pk %}">Edit details</a>
    <a href="{% url 'baz_scheduler:employee-create' %}">Add an employee</a>
    <a href="{% url 'baz_scheduler:employee-delete' obj.pk %}">Delete the employee</a>
</body>
</html>

baz_scheduler/templates/baz_scheduler/sent_baz_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete sent-baz?</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Delete">Delete</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/sent_baz_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create swent-baz</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Create</button>
    </form>
</body>
</html>

baz_scheduler/templates/baz_scheduler/sent_baz_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sent-baz details</title>
</head>
<body>
    Sent-baz name = {{ obj.name }}
    <br />
    <a href="{% url 'baz_scheduler:sent-baz-update' obj.pk %}">Edit</a>
    <a href="{% url 'baz_scheduler:sent-baz-create' %}">Create a new sent-baz</a>
    <a href="{% url 'baz_scheduler:sent-baz-delete' obj.pk %}">Delete the sent-baz</a>
</body>
</html>

baz_scheduler/templates/baz_scheduler/sent_baz_update_form copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update sent-baz</title>
</head>
<body>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Update</button>
    </form>
</body>
</html>